### ISSUE TITLE
Kafka Connect won't start when setting vaultprovider class

### ISSUE THREAD

**Issue by evaisman-tc** [lensesio/secret-provider#18]
Hey guys, I'm trying to use the VaultSecretProvider withiin my connect cluster (distributed).

Here is how I add it to my docker configs:

image: `confluentinc/cp-kafka-connect-base:5.5.2"`

I've placed the secret provider `secret-provider-2.1.5-all.jar` in `/local/secret-providers`

```
CONNECT_PLUGIN_PATH: "/usr/share/java,/connect-plugins,/usr/share/confluent-hub-components,/local/connector-plugins,/local/secret-providers"
CONNECT_CONFIG_PROVIDERS: "vault"
CONNECT_CONFIG_PROVIDERS_VAULT_CLASS: "io.lenses.connect.secrets.providers.VaultSecretProvider"
CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_ADDR: "url"
CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_AUTH_METHOD: "token"
CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_TOKEN: "${VAULT_TOKEN}"
CONNECT_CONFIG_PROVIDERS_VAULT_PARAM_FILE_DIR: "local/connector-files/vault"
```

the resulting properties file becomes:
```
plugin.path=/usr/share/java,/connect-plugins,/usr/share/confluent-hub-components,/local/connector-plugins,/local/secret-providers
config.providers.vault.param.token=<token>
config.providers.vault.param.auth.method=token
config.providers.vault.param.file.dir=local/connector-files/vault
config.providers.vault.param.addr=url
config.providers.vault.class=io.lenses.connect.secrets.providers.VaultSecretProvider
config.providers=vault
```

However, on startup I end up with the following stacktrace
```
[main] ERROR io.confluent.admin.utils.cli.KafkaReadyCommand - Error while running kafka-ready.
org.apache.kafka.common.config.ConfigException: Invalid value java.lang.ClassNotFoundException: io.lenses.connect.secrets.providers.VaultSecretProvider for configuration Invalid config:io.lenses.connect.secrets.providers.VaultSecretProvider ClassNotFoundException exception occurred
        at org.apache.kafka.common.config.AbstractConfig.instantiateConfigProviders(AbstractConfig.java:538)
        at org.apache.kafka.common.config.AbstractConfig.resolveConfigVariables(AbstractConfig.java:477)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:107)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
        at org.apache.kafka.clients.admin.AdminClientConfig.<init>(AdminClientConfig.java:216)
        at org.apache.kafka.clients.admin.Admin.create(Admin.java:71)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
        at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138)
        at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
```

If I was to remove the `config.providers=vault` I instead see this line within the connect logs 

```
[2021-01-28 20:16:59,022] INFO Added plugin 'io.lenses.connect.secrets.providers.VaultSecretProvider' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

Any suggestions? Thanks!

**Comment by evaisman-tc** [comment]
Ah, turns out the confluent docker image has a faulty start script. For those who run into the same issue see: https://github.com/confluentinc/cp-docker-images/issues/828.

I chose to overwrite the entrypoint to not call `ensure` in https://github.com/confluentinc/kafka-images/blob/master/kafka-connect-base/include/etc/confluent/docker/run
